;--------------------------------------------------------------------------------------------
; RAINMETER UPDATER

[Variables]
RegExp=(?(?=.*vt id col_0).*<a href="detail\?name=Rainmeter-(.*)-.*.exe&amp.*32bit/64bi(.*)ersion.*revision(.*)\n)
AvailableVersion=AvailableVersion_02
ShowRevision=Revision_02
AvailableDownload=AvailableDownload_02
ChangeCheckBeta=0
CheckBeta=1
BetaRelease=BetaRelease_02
Icon=Up to date
IconBeta=_beta
