[Variables]
; GENERAL
GmailUsername=YourUsernameHere
GmailPassword=YourPasswordHere
TwitterUsername=YourUsernameHere
TwitterPassword=YourPasswordHere
MusicPlayer=WMP
Drive1=C
Drive2=E
Drive3=F
NetworkMaxDownload=1000000
NetworkMaxUpload=500000
CalendarExtraDays=1
GalleryPath=C:\Users\SND\Downloads\ImageS
GalleryPreserveRatio=1
GalleryTime=60
; LAYOUT
Stylesheet=Enigma Dark
; APPS
App1=Firefox
App1Path=firefox.exe
App1Label=BROWSER
App1Icon=#SKINSPATH#Enigma\Resources\Images\Launcher\Firefox.#ColorImage#.png
App2=Notepad
App2Path=notepad.exe
App2Label=TEXT
App2Icon=#SKINSPATH#Enigma\Resources\Images\Launcher\Text.#ColorImage#.png
App3=GAMING MODE
App3Path=...
App3Label=
App3Icon=C:\Users\SND\Documents\Documents\My Icons\2k11\Gamepad
App4=Downloads
App4Path=D:\DownloadS\
App4Label=CHAT
App4Icon=#SKINSPATH#Enigma\Resources\Images\Launcher\Chat.#ColorImage#.png
App5=Google Images
App5Path=D:\Google Images\
App5Label=Web
App5Icon=#SKINSPATH#Enigma\Resources\Images\Launcher\Rainmeter.png
; FEEDS
Feed1=http://news.google.com/news?pz=1&ned=us&hl=en&topic=h&num=10&output=rss
Feed1Type=1
Feed1RegExp=#RegExpRSS#
Feed2=http://rainmeter.net/forum/feed.php
Feed2Type=2
Feed2RegExp=#RegExpAtom#
Feed3=http://feeds.gawker.com/lifehacker/excerpts.xml
Feed3Type=1
Feed3RegExp=#RegExpRSS#
FacebookFeed=http://www.facebook.com/feeds/notifications.php?id=100003181051791&viewer=100003181051791&key=AWiHmJK3reT98crl&format=rss20
GoogleCalendar1=YourCalendarAddressHere
GoogleCalendar2=YourCalendarAddressHere
GoogleCalendar3=YourCalendarAddressHere
RTMusername=
RTMpassword=
RTMlist1=YourListNumberHere
RTMlist2=YourListNumberHere
RTMlist3=YourListNumberHere
ReaderInterval=30
; NOTES
Note1Title=Notes
Note1Path=#SKINSPATH#Enigma\Sidebar\Notes\Notes1.txt
Note2Title=Tasks
Note2Path=#SKINSPATH#Enigma\Sidebar\Notes\Notes2.txt
Note3Title=About
Note3Path=#SKINSPATH#Enigma\Sidebar\Notes\Notes3.txt
NoteHeight=200
NoteDisablePages=0
; WORLD
WeatherCode=YourWeatherCodeHere
Unit=c
World1WeatherCode=UKXX0085
World1DSTOffset=-1
World2WeatherCode=IRXX0018
World2DSTOffset=-0.5
World3WeatherCode=ISXX0010
World3DSTOffset=-1
; OTHER
; Please do not change these.
RainWrite=#ADDONSPATH#RainWrite\RainWrite.exe
RainRGB=#ADDONSPATH#RainRGB3\RainRGB.exe
UserVariables=#SKINSPATH#Enigma\Resources\Variables\UserVariables.inc
