[Variables]
; ----------------------------------------------------------------------#
; Drives White															#
; ----------------------------------------------------------------------#
FontColorMeter=235,235,225,255
FontColorBar=235,235,225,25
FontEffectShadow=20,20,20,220
FontName=GeosansLight
FontNameBold=GeosansLight Medium
FontSizeBig=11
FontSizeMid=9
FontSizeSmall=7
; ----------------------------------------------------------------------#
; Drives Dark															#
; ----------------------------------------------------------------------#

