; ----------------------------------------------------------------------#
;Big Drives																#
; ----------------------------------------------------------------------#
[Sty1White_HDBarBackDiv]
X=10
Y=47
W=75
H=2
SolidColor=#FontColorBar#

[Sty1White_HDRightFree]
X=160
Y=5
;W=0
;H=0
StringAlign=Right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=#FontEffectShadow#
FontColor=#FontColorMeter#
FontFace=#FontNameBold#
FontSize=#FontSizebig#
AntiAlias=1
ClipString=1
AutoScale=1
NumOfDecimals=1
Percentual=0

[Sty1White_HDRightTotal]
X=0r
Y=18r
;W=0
;H=0
StringAlign=Right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=#FontEffectShadow#
FontColor=#FontColorMeter#
FontFace=#FontNameBold#
FontSize=#FontSizeMid#
AntiAlias=1
ClipString=1
AutoScale=1
NumOfDecimals=1
Percentual=0

; ----------------------------------------------------------------------#
;Small Drives															#
; ----------------------------------------------------------------------#
[Sty2White_HDBarBackDiv]
X=5
Y=30
W=45
H=2
SolidColor=#FontColorBar#

[Sty2White_HDRightFree]
X=115
Y=2
;W=0
;H=0
StringAlign=Right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=#FontEffectShadow#
FontColor=#FontColorMeter#
FontFace=#FontNameBold#
FontSize=#FontSizeMid#
AntiAlias=1
ClipString=1
AutoScale=1
NumOfDecimals=1
Percentual=0

[Sty2White_HDRightTotal]
X=0r
Y=15r
;W=0
;H=0
StringAlign=Right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=#FontEffectShadow#
FontColor=#FontColorMeter#
FontFace=#FontNameBold#
FontSize=#FontSizeSmall#
AntiAlias=1
ClipString=1
AutoScale=1
NumOfDecimals=1
Percentual=0
